only echo test

diff --git a/.github/workflows/pr_file_size.yml b/.github/workflows/pr_file_size.yml
--- a/.github/workflows/pr_file_size.yml
+++ b/.github/workflows/pr_file_size.yml
@@ -21,17 +21,18 @@ jobs:
           SIZE_LIMIT=$((10*1024*1024))
 
           # Get the list of changed files in the pull request
+          echo "Testing output"
           CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
           echo "$CHANGED_FILES"
           # Iterate through each changed file
-          for FILE in $CHANGED_FILES; do
-            # Check if the file size exceeds the limit
-            FILE_SIZE=$(wc -c < "$FILE")
-            if [ "$FILE_SIZE" -gt "$SIZE_LIMIT" ]; then
-              echo "Error: File $FILE exceeds the size limit of 10MB."
-              exit 1
-            else
-              echo "Pass $FILE"
-            fi
-          done
+          #for FILE in $CHANGED_FILES; do
+          #  # Check if the file size exceeds the limit
+          #  FILE_SIZE=$(wc -c < "$FILE")
+          #  if [ "$FILE_SIZE" -gt "$SIZE_LIMIT" ]; then
+          #    echo "Error: File $FILE exceeds the size limit of 10MB."
+          #    exit 1
+          #  else
+          #    echo "Pass $FILE"
+          #  fi
+          #done
         shell: bash
